import Sidebar from '@/components/Sidebar'
import '@/styles/globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
        <Sidebar />
        {children}
        </body>
    </html>
  )
}
